apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojis-app
spec:
  selector:
    matchLabels:
      app: emojis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: emojis-app
    spec:
      containers:
      - name: emojis-app
        image: emojis-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: emojis
  labels:
    app: emojis-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: application
  - port: 8081
    protocol: TCP
    name: administration
  selector:
    app: emojis-app
---
